name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Make bin/rails and bin/rubocop executable
        run: chmod +x bin/rails bin/rubocop

      - name: Check permissions of bin/rails and bin/rubocop
        run: ls -l bin/rails bin/rubocop

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Make bin/rubocop executable
        run: chmod +x bin/rubocop

      - name: Check permissions of bin/rubocop
        run: ls -l bin/rubocop

      - name: Lint Ruby files
        run: bin/rubocop -f github
